import {growColony,readyToReproduce} from '../dist/life-history.js';
import {develop} from '../dist/development.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {World} from '../dist/engine.js';
import {phenotype,traitClosure} from '../dist/biology.js';
import {inventory,balances,synthesize,ingest,spend,eatPrey,diffuseResources,N_RATIO} from '../dist/ecology.js';
const world=()=>new World({origin:false,founders:2,seed:'CYCLE-19',mutation:0});
function checkOperation(w,fn){const before=inventory(w),l={...w.ecology};fn();const after=inventory(w),e=w.ecology;assert.ok(Math.abs(after.energy-before.energy-(e.energyIn-l.energyIn)+(e.heat-l.heat)+(e.energyOut-l.energyOut))<1e-8);assert.ok(Math.abs(after.nutrient-before.nutrient-(e.nutrientIn-l.nutrientIn)+(e.nutrientOut-l.nutrientOut))<1e-8);}
test('paused environment changes and climate events do not inject or consume resources',()=>{const w=world(),before=inventory(w),pools=structuredClone(w.fields.map(f=>[f.nutrient,f.redox,f.plankton,f.detritus,f.photons]));w.trigger('winter');w.config.light=2;w.updateEnvironment();assert.deepEqual(inventory(w),before);assert.deepEqual(w.fields.map(f=>[f.nutrient,f.redox,f.plankton,f.detritus,f.photons]),pools);});
test('photosynthesis and chemical synthesis conserve energy and N, including full storage',()=>{for(const source of ['photons','redox','radiant']){const w=world(),a=w.agents[0],f=w.fieldAt(a.x,a.y);f[source]=10;f.nutrient=1;a.energy=41.99;checkOperation(w,()=>synthesize(w,a,f,source,10,.8));assert.ok(a.energy<=42);assert.ok(f[source]>9);f.nutrient=0;const before=a.energy;assert.equal(synthesize(w,a,f,source,10,.8),0);assert.equal(a.energy,before);}});
test('feeding waste, respiration, death and predation preserve matter and energy accounting',()=>{const w=world(),a=w.agents[0],b=w.agents[30],f=w.fieldAt(a.x,a.y);f.plankton=10;f.detritus=10;checkOperation(w,()=>ingest(w,a,f,'plankton',3,.7));checkOperation(w,()=>ingest(w,a,f,'detritus',3,.7));checkOperation(w,()=>spend(w,a,.5));checkOperation(w,()=>{eatPrey(w,a,b);w.kill(b,'捕食');});const once=inventory(w);w.kill(b,'捕食');assert.deepEqual(inventory(w),once);checkOperation(w,()=>spend(w,a,100));assert.equal(a.energy,0);checkOperation(w,()=>w.kill(a,'饥饿'));});
test('reproduction pays for mutated structure and parental care as well as child reserves',()=>{for(const traits of [[],traitClosure(['budding']),traitClosure(['brood'])]){const w=world(),a=w.agents[0],b=w.agents[1];a.traits=traits;a.structureGenes=[...a.traits];a.form=phenotype(traits);Object.assign(a,{energy:40,age:50,cooldown:0});Object.assign(b,{energy:40,age:50,cooldown:0,x:a.x,y:a.y});a.development=develop(a);while(!readyToReproduce(a)){a.age+=12-a.age%12;growColony(w,a);}w.config.mutation=.3;let child;checkOperation(w,()=>child=w.reproduce(a,[b]));assert.ok(child?.bodyEnergy>0);}});
test('linked complex organs have a 50 percent inheritance chance independent of chain depth',()=>{const w=world(),a=w.agents[0],b=w.agents[1];a.traits=traitClosure(['camera']);a.structureGenes=[...a.traits];b.traits=[];b.structureGenes=[...b.traits];let count=0;for(let i=0;i<10000;i++)count+=w.inherit(a,b).traits.includes('camera');assert.ok(count>4750&&count<5250,`${count}/10000`);});
test('resource diffusion preserves totals and nonnegative pools across land and ocean',()=>{const fields=Array.from({length:12},(_,i)=>({land:i<6,nutrient:i===3?12:0,redox:i===11?5:0,plankton:i===0?4:0,detritus:i===8?3:0}));const keys=['nutrient','redox','plankton','detritus'],totals=keys.map(k=>fields.reduce((n,f)=>n+f[k],0));for(let t=0;t<500;t++)diffuseResources(fields,4,3);keys.forEach((k,i)=>assert.ok(Math.abs(fields.reduce((n,f)=>n+f[k],0)-totals[i])<1e-10));assert.ok(fields.every(f=>keys.every(k=>f[k]>=0)));});
test('origin, natural evolution, environmental shocks and reload retain closed accounting',()=>{const w=new World({seed:'LEDGER-9'});w.step(1300);w.trigger('meteor');w.trigger('drought');w.trigger('radiation');w.step(1700);const saved=World.restore(w.serialize());w.step(600);saved.step(600);assert.deepEqual(saved.ecology,w.ecology);assert.deepEqual(saved.foodWeb,w.foodWeb);for(const v of Object.values(balances(w)))assert.ok(Number.isFinite(v));assert.ok(Math.abs(balances(w).energyError)<.0001);assert.ok(Math.abs(balances(w).nutrientError)<.00001);});
test('a dead entry cannot silently block births before end-of-step cleanup',()=>{const w=world(),a=w.agents[0],dead=w.agents[1];w.capacity=w.agents.length;w.kill(dead,'灾变');Object.assign(a,{energy:35,age:60,cooldown:0});assert.ok(w.reproduce(a,[]));assert.equal(w.liveCount,w.capacity);});
